#!/usr/bin/env bash
# A Bash script that lists all processes in tree format with columns USER, STARTED, and CMD

ps -eo user,lstart,cmd --forest | awk 'NR==1{$2="STARTED"; $3=$4=$5=""; $6=""; $7=""; $8="CMD"}1'
