#!/usr/bin/env bash
# Script to attempt to stop the 7-highlander process

# Find the PID(s) of the 7-highlander process
pid=$(pgrep -f 7-highlander)

# Send SIGTERM using `kill`
[ -n "$pid" ] && kill "$pid"
