#!/usr/bin/env bash
# A Bash script that forcefully kills the 7-highlander process using SIGKILL

# Find the PID of 7-highlander
pid=$(pgrep -f 7-highlander)

# Kill the process using SIGKILL (signal 9)
[ -n "$pid" ] && kill -9 "$pid"
